name: playx_localization
description: Easily manage and update app localization with a simple implementation and a lot of utilities.
version: 0.2.1
homepage: https://github.com/playx-flutter/playx_localization
repository: https://github.com/playx-flutter/playx_localization
issue_tracker: https://github.com/playx-flutter/playx_localization/issues
topics:
  - playx
  - localization
  - translation
  - internationalization

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  playx_core: ^0.5.5
  intl: ^0.19.0
  easy_localization: ^3.0.7
  shared_preferences_platform_interface: ^2.4.1

dependency_overrides:
  win32: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.1.1

flutter:
